name: Pull Request checks

on:
  workflow_call:
    inputs:
      python_version:
        default: "3.8"
        required: false
        type: string
      flake8_workdir:
        default: "."
        required: false
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - uses: reviewdog/action-flake8@v3
        with:
          github_token: ${{ inputs.secrets.GITHUB_TOKEN }}
          flake8_args: --config=.flake8 gulfstream
          reporter: github-pr-review
          workdir: ${{ inputs.flake8_workdir }}
          fail_on_error: true

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python_version }}
      - uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ inputs.secrets.GITHUB_TOKEN }}
